"""added new car fields

Revision ID: 41c8fdcff9ea
Revises: 
Create Date: 2025-05-14 14:59:19.213495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41c8fdcff9ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eficiencia_combustible', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emisiones_co2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_bateria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tiempo_carga', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salud_bateria', sa.Integer(), nullable=True))
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('autonomia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autonomia', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('model',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('marca',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('salud_bateria')
        batch_op.drop_column('tiempo_carga')
        batch_op.drop_column('capacidad_bateria')
        batch_op.drop_column('emisiones_co2')
        batch_op.drop_column('eficiencia_combustible')

    # ### end Alembic commands ###
