"""Add sold status to cars

Revision ID: 9c56a3a3467b
Revises: 41c8fdcff9ea
Create Date: 2025-05-17 00:44:59.363217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c56a3a3467b'
down_revision = '41c8fdcff9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venut', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotxes', schema=None) as batch_op:
        batch_op.drop_column('venut')

    # ### end Alembic commands ###
